[package]
name = "musli"
version = "0.0.39"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.65"
description = """
Müsli is a flexible and generic binary serialization framework.
"""
documentation = "https://docs.rs/musli"
readme = "README.md"
homepage = "https://github.com/udoprog/musli"
repository = "https://github.com/udoprog/musli"
license = "MIT/Apache-2.0"
keywords = ["no_std", "serialization"]
categories = ["encoding"]

[features]
default = ["std"]
std = []

[dependencies]
musli-macros = { version = "=0.0.39", path = "../musli-macros" }

[dev-dependencies]
musli-wire = { path = "../musli-wire", default-features = false }
musli-storage = { path = "../musli-storage", default-features = false }
musli-json = { path = "../musli-json", default-features = false, features = ["std"] }
